export const LEGAL = {
    terms: {
        title: 'Terms & Conditions',
        lastUpdated: 'February 03, 2025',
        sections: [
            {
                title: '1. Introduction',
                content: 
`
Please read these Terms of Service (the “<strong>Terms of Service</strong>”) carefully because they govern all access to and use of the website and the user interface located <a href="https://game7.io/" target="_blank">here</a> (the “<strong>Site</strong>”), and the Game7 network (the “<strong>Game7 Network</strong>”), which is a “layer-3” network that operates on top of the Arbitrum One “layer-2” network (“<strong>Arbitrum</strong>”), which operates on top of the “layer-1” Ethereum blockchain (“<strong>Ethereum</strong>”), including all other content, functionality, and services offered by Game 7 DAO Ltd., a British Virgin Islands company and its subsidiaries, doing business as Game7 (“<strong>Game7</strong>”, “<strong>we</strong>”, “<strong>us</strong>” or “<strong>our</strong>”) (the “<strong>Protocol</strong>”). To make these Terms of Service easier to read, the Site and the Protocol, including all existing and any updated or new features, functionality, and technology, are collectively called the <strong>Services.</strong>” Please note that the Services may facilitate interaction with decentralized cryptographic protocols maintained by third-party open-source communities which we do not own or control. These Terms of Service apply to any other website operated by Game7 on which these Terms of Service are posted. These Terms of Service, together with the <strong>“Airdrop Terms and Conditions</strong>”, are collectively called the “<strong>Terms.</strong>” The Airdrop Terms and Conditions are available here, and are incorporated by reference as though fully set forth herein.
All access and use of our Services is subject to these Terms. By accessing, browsing, or otherwise using the Site, the Protocol, or any other aspect of our Services, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you are using our Services on behalf of an entity or other organization, you are agreeing to these Terms on behalf of that entity or organization and representing to Game7 that you have the authority to bind that entity or organization to these Terms (and, in which case, the terms “<strong>you</strong>” and “<strong>your</strong>” will refer to that entity or organization). If you do not accept the terms and conditions of these Terms, you are prohibited from accessing, browsing, or otherwise using our Services.
`,
            },
            {
                title: '2. Service Restrictions',
                content: 
`
THE SERVICES ARE NOT OFFERED TO AND MAY NOT BE USED BY: PERSONS OR ENTITIES WHO RESIDE IN, ARE CITIZENS OF, ARE LOCATED IN, ARE INCORPORATED IN, OR HAVE A REGISTERED OFFICE IN ANY RESTRICTED TERRITORY, AS DEFINED BELOW (EACH SUCH PERSON OR ENTITY FROM A RESTRICTED TERRITORY, A “<strong>RESTRICTED PERSON</strong>”).
BY USING THE SERVICES, YOU REPRESENT THAT YOU ARE NOT A RESTRICTED PERSON AND ARE NOT A PERSON OR ENTITY WHO IS RESIDENT IN, A CITIZEN OF, IS LOCATED IN, IS INCORPORATED IN, OR HAS A REGISTERED OFFICE IN ANY RESTRICTED TERRITORY, AS DEFINED BELOW. ADDITIONALLY, IF YOU RESIDE IN THE UNITED STATES, YOU MAY NOT BE ALLOWED TO USE CERTAIN FEATURES OR FUNCTIONS OF THE SERVICES.
IMPORTANT NOTICE REGARDING ARBITRATION: BY ACCEPTING THESE TERMS YOU ARE AGREEING (WITH LIMITED EXCEPTION) TO RESOLVE ANY DISPUTE BETWEEN YOU AND GAME7 THROUGH BINDING, INDIVIDUAL ARBITRATION RATHER THAN IN COURT. PLEASE REVIEW CAREFULLY SECTION 16 (DISPUTE RESOLUTION) BELOW FOR DETAILS REGARDING ARBITRATION. HOWEVER, IF YOU ARE A RESIDENT OF A JURISDICTION WHERE APPLICABLE LAW PROHIBITS ARBITRATION OF DISPUTES, THE AGREEMENT TO ARBITRATE IN SECTION 16 WILL NOT APPLY TO YOU, BUT THE PROVISIONS OF SECTION 15 (GOVERNING LAW AND FORUM) WILL APPLY INSTEAD.
`
            },
            {
                title: '3. Agreement to Terms',
                content: 'By accessing or using the Services, you agree to be bound by these Terms. If you do not agree to be bound by these Terms, you are not authorized to use the Services.'
            },
            {
                title: '4. Privacy Policy',
                content: 'Please review our Privacy Policy (available <a href="https://game7.io/privacy" target="_blank">here</a>), which also governs your use of the Services, for information on how we collect, use, and share your information.'
            },
            {
                title: '5. Changes to these Terms or the Services',
                content: 'We may update the Terms, including any addendum terms, from time to time in our sole discretion. If we do, we will post the updated Terms on this page and will indicate at the top of this page the date these Terms were last revised. It is important that you review the Terms whenever we update them, or whenever you use the Services. If you continue to use the Services after we have posted updated Terms it means that you accept and agree to the changes. If you do not agree to be bound by the changes, you may not use the Services anymore. We may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion.'
            },
            {
                title: '6. Who May Use the Services?',
                content: 
`
YOU MAY USE THE SERVICES ONLY IF YOU ARE 18 YEARS OR OLDER AND CAPABLE OF FORMING A BINDING CONTRACT WITH GAME7, HAVE A DIGITAL WALLET (AS DEFINED BELOW), AND ARE NOT OTHERWISE BARRED FROM USING THE SERVICES UNDER APPLICABLE LAW.
For certain features of the Services, you will need to create a Game7 account. You are responsible for all activities that occur under your Game7 account. The Services are only offered to users in certain jurisdictions who can use the Services as permitted under applicable law. You certify that you will comply with all applicable laws, rules, and regulations when using the Services. Without limiting the foregoing, by using the Services, you represent and warrant that: (a) You are not a resident, national, or agent of North Korea, Iran, Syria, Belarus, Cuba, Russia, and the Crimea, Luhansk, Donetsk, Zaporizhzhia, and Kherson regions of Ukraine, or any other country or jurisdiction to which the United States, the United Nations Security Council, or the European Union embargoes goods or imposes similar sanctions (collectively, “<strong>Restricted Territories</strong>”); (b) You are not a member of any sanctions list or equivalent established by the British Virgin Islands, the United Kingdom, United States, the United Nations Security Council, or the European Union (collectively, “<strong>Restricted Persons</strong>”) and you do not intend to transact with any Restricted Person; and (c) You do not, and will not, use VPN software or any other privacy or anonymization tools or techniques to circumvent, or attempt to circumvent, any restrictions that apply to the Services.
Game7 may require you to provide additional information and documents regarding your use of the Services, including at the request of any competent authority or in case of application of any applicable law or regulation, including laws related to anti-money laundering or for counteracting terrorist financing. Game7 may also require you to provide additional information or documents in cases where it has reason to believe: (i) that you are a Restricted Person or a resident or national of a Restricted Territory; (ii) that your Digital Wallet (as defined below) is being used for money laundering or for any other illegal activity; or (iii) you have concealed or reported false identification information or other details.
`
            },
            {
                title: '7. About the Services',
                content: 
`
<h4>a.	Digital Wallet</h4>
To access and participate in the Services, you will need to connect a supported third-party digital asset wallet, such as MetaMask or Coinbase Wallet (a “<strong>Digital Wallet</strong>”), to the Services. All Digital Wallet services are Third-Party Services (as defined below) within the meaning of these Terms. By using a Digital Wallet in connection with the Services, you agree that you are using that wallet under the terms and conditions of the applicable third-party provider of the wallet. Digital Wallets are not operated by, maintained by, or affiliated with Game7, and Game7 does not have custody or control over the contents and assets of any Digital Wallet, and does not have the ability to retrieve or transfer the contents or assets of any Digital Wallet. Game7 accepts no responsibility for, or liability to you, in connection with your use of any Digital Wallet, and makes no representations or warranties regarding how the Services will operate with any specific Digital Wallet. 
If you elect to purchase any digital asset, or make a payment for Services using any digital asset, through the Digital Wallet that you have connected to the Services (collectively, “<strong>Payments</strong>”), you acknowledge and agree that any such transactions will be conducted solely through the blockchain network governing the digital asset and that Game7 has no control over such Payments, nor does Game7 have the ability to reverse any such Payments. You acknowledge and agree that certain Payments transactions may be carried out by Third-Party Services (as defined below), such as those offered and provided at <a href="https://getsome.game7.io/" target="_blank">https://getsome.game7.io/</a>, and that Game7 has no control over such Payments, nor does Game7 have the ability to reverse any such Payments. Accordingly, Game7 will have no liability to you or to any third-party for any claims or damages that may arise as a result of any Payments or other transactions that you make through the Services. In certain cases, your transactions through the Services may not be successful due to an error with the Digital Wallet. Game7 accepts no responsibility or liability to you for any such failed transactions, or any transaction or gas fees that may be incurred by you in connection with such failed transactions. You are solely responsible for keeping your Digital Wallet secure, and you should never share your Digital Wallet credentials, private key or seed phrase with anyone. If you discover an issue related to your Digital Wallet, please contact the third-party Digital Wallet provider.
<h4>b.	Quests and Lootdrops</h4>
The Services may enable you to access certain interactive tasks, events, and/or contests made available by Game7 (each, a “<strong>Quest</strong>”). Quests may be offered as a collection or grouping of related actions or prompts called a lootdrop (“<strong>Lootdrop</strong>”). By participating in and/or completing Quests or Lootdrops, you may be offered rewards or other benefits, as communicated to you through the Services in connection with each such Quest or Lootdrop. You agree and acknowledge that Quests or Lootdrops may be offered by third-parties, including associated rewards or other benefits related to such third-party Quests or Lootdrops. You agree and acknowledge that your participation in any Quest or Lootdrop, and eligibility for any related rewards or other benefits, may be subject to additional terms, including third-party terms, and you agree to comply with all such terms. For Quests or Lootdrops that are offered by third-parties and/or rely upon third-party technology, Game7 may not be held responsible for any disruptions, malfunctions, or errors that may prevent you from completing a Quest or Lootdrop, or earning or receiving any associated rewards or other benefits. If a Quest or Lootdrop is offered by a third-party, such third-party is solely responsible for the distribution of any related rewards or other benefits to you, and Game7 does not guarantee the availability, delivery, or legitimacy of such third-party rewards or other benefits. YOU BEAR FULL RESPONSIBILITY FOR VERIFYING THE LEGITIMACY AND AUTHENTICITY OF QUEST AND LOOTDROP REWARDS, INCLUDING DIGITAL ASSETS, YOU RECEIVE THROUGH THE SERVICES.
<h4>c.	Diamonds and G7 Boxes</h4>
In connection with your access to or use of the Services you may be offered the opportunity to receive Game7 Diamonds (“<strong>Diamonds</strong>”). Diamonds are non-transferable, revocable incentives issued by Game7 through participation in Quests, Lootdrops, Staking (as defined below), and other third party events, actions, and promotions. Diamonds cannot be transferred, cannot be exchanged for cash, and have no cash value. The number of Diamonds earned or received may vary depending on the nature of your interaction with the Services, including the Site and the Protocol. Game7 reserves the right to determine, in its sole discretion, the number of Diamonds awarded for any given interaction. In connection with your access to or use of the Services, you may also be offered the opportunity to earn Diamonds by Staking (as defined below) G7 Tokens. Diamonds may be used to acquire rewards and gaming assets in the Game7 Diamond Store (“<strong>Diamond Store</strong>”), including Game7 Boxes (“<strong>G7 Boxes</strong>”). G7 Boxes may contain items such as digital assets or tokens, including non-fungible tokens (“<strong>NFTs</strong>”), in-game assets, and/or access to exclusive Game7 and partner rewards, gear, events, and other special offers (collectively, “<strong>G7 Box Rewards</strong>”). Each G7 Box contains pre-determined G7 Box Rewards. When you redeem Diamonds for a G7 Box, you will be randomly assigned a specific G7 Box that contains pre-determined G7 Box Rewards. All rewards and benefits offered through G7 Boxes are distributed randomly. No actions taken or consideration provided will alter the rewards or benefits received from a G7 Box or the likelihood of receiving a reward or benefit. Participation in G7 Boxes is only available through the use of Diamonds, and not through any fiat currency or other item of monetary value. G7 Boxes may contain virtual items provided for use exclusively within the Service or within a Third-Party Service (as defined below). All such exclusive items have no monetary value and cannot be redeemed for cash or equivalent, and you are granted a non-transferable, non-exclusive, revocable license to use the items as permitted under these Terms or those terms of the Third-Party Service (as defined below), as applicable. Once Diamonds are redeemed for a G7 Box the action is irreversible. Once a G7 Box is opened the action is irreversible. The Diamond Store may impose a time delay between the time Diamonds are redeemed for a G7 Box, and the time that the acquired G7 Box may be opened.
<h4>d.	Staking and Governance</h4>
In connection with your access to or use of the Services, you may be offered the opportunity to lock up (“<strong>Stake</strong>” or “<strong>Staking</strong>”) certain digital assets or tokens, including G7 Tokens, for a set period (“<strong>Lockup Period</strong>”), which prevents the transfer of the digital assets or tokens for that set period of time. You acknowledge and agree that any digital assets or tokens which you have Staked may not be available for you to transfer or withdraw to your Digital Wallet (“<strong>Withdrawal</strong>”) during the applicable Lockup Period, including any applicable cool-down period (“<strong>Cool-Down Period</strong>”) in which the digital assets or tokens remain temporarily subject to a Lockup Period following the submission of a Withdrawal transaction. Further, the Services may allow you to vote on certain community actions, submit proposals for community actions or otherwise participate in other collective decisions (such process, “<strong>Community Governance</strong>”). Staking and Community Governance may only be offered in accordance with the rules of the Game7 Protocol.
<h4>e.	The Protocol and Fees</h4>
The Game7 Protocol enables users to do various things such as processing Ethereum and Arbitrum transactions more efficiently, passing information between or amongst the Ethereum, Arbitrum and the Game7 Mainnet blockchains (i.e. bridging), Staking certain digital assets or tokens, participating in Community Governance, and interacting with third-party smart contract-based applications that are built on the Game7 Mainnet. By accessing or using the Protocol, you may be charged applicable fees, including any fees required to execute any Protocol transaction, such as transaction, processing, or hosting fees, blockchain gas, or similar network fees (collectively, “<strong>Transaction Fees</strong>”). We will disclose an estimate of the amount of Transaction Fees we will charge or pass through to you for the applicable Service at the time you access, use, or otherwise transact with the Services, however, the final amount of such Transaction Fees will only be known and determined after a transaction is processed. Although we will attempt to provide accurate Transaction Fee information, any such information reflects our estimate of such fees, which may vary from the fees actually paid to use the Services and interact with the applicable blockchain with which the Services are compatible. In addition, your Digital Wallet provider may impose a fee to transact on the Services. Game7 is not responsible for any fees charged by a third party (“<strong>Third-Party Fees</strong>”). You agree to pay any applicable fees, including Transaction Fees, Third-Party Fees, and hosting fees, in connection with your use of and transactions using the Services. All transactions processed through the Services are non-refundable.
<h4>f.	Game7 DevHub</h4>
Game7’s mission is to build and expand the blockchain gaming ecosystem, and as such it prioritizes fostering, growing, and incentivizing a community of developers who desire and are able to test, build on, and improve the Services, including the Protocol and its related products, applications, and services. Game7’s Developer Hub (available <a href="https://build.game7.io/" target="_blank">here</a>) (“<strong>DevHub</strong>”) provides access to and use of certain Sites, software, technologies, features, and other online products and services provided to developers by Game7, including but not limited to products and services for the Game7 Testnet, Faucet, and Bridge, as well as related Third-Party Services (as defined below) (collectively, the “<strong>DevHub Program</strong>”). For information regarding the scope, offerings and other details of the DevHub Program please refer to the additional DevHub documentation (available <a href="https://docs.game7.io/" target="_blank">here</a>) (“<strong>DevHub Documents</strong>”). From time to time, Game7 may announce various DevHub Program contribution opportunities, for example, in the form of hackathons, requests for grant proposals, on-chain incentives, and live events, and the goals Game7 intends to pursue with each. For information regarding the scope, criteria, rewards, selection process, and other details for each DevHub Program contribution opportunity, please refer to the specific announcement detailing the particular opportunity and any additional documentation that may be provided. YOUR PARTICIPATION IN THE DEVHUB PROGRAM IS ENTIRELY VOLUNTARY, AND IF YOU PARTICIPATE IN THE DEVHUB PROGRAM YOU MUST STRICTLY ADHERE TO THESE TERMS.
<h4>g.	Feedback</h4>
Game7 appreciates feedback, comments, ideas, proposals and suggestions for improvements to the Services (“<strong>Feedback</strong>”). If you choose to submit Feedback, you grant Game7 a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sublicensable and transferable license under any and all intellectual property or other rights that you own or control to use, copy, modify, create derivative works based upon, make, have made, sell, offer for sale, import and otherwise exploit in any manner or medium whatsoever known now or in the future, your Feedback for any purpose, without compensation to you. For the avoidance of doubt, and to the extent permissible, Feedback includes any feedback, comments, ideas, proposals or suggestions provided to, or accessed by, Game7 through any Third-Party Content or Third-Party Services (as those terms are defined below).
<h4>h.	Restricted Services</h4>
The Services may also allow you to participate in and initiate certain transactions of digital assets using your Digital Wallet, including without limitation Payments using your Digital Wallet, the Withdrawal of tokens or other assets to your Digital Wallet, exchanging one type of digital asset or token for another (“<strong>Swapping</strong>”) using your Digital Wallet.
<h4>i.	Third-Party Content and Services</h4>
The Site may allow you to view, access, use, or interact with certain informational content and resources of one or more third parties (collectively, “<strong>Third-Party Content</strong>”), and certain websites, products, integrations, applications, services and protocol functionality of one or more third parties (collectively, “<strong>Third-Party Services</strong>”), including but not limited to Arbitrum, Ethereum, Digital Wallets, Discord, Conduit, Relay.Link, thirdweb, and Camelot Exchange. Use of Arbitrum is subject to the Arbitrum terms and conditions (<a href="https://arbitrum.foundation/tos" target="_blank">https://arbitrum.foundation/tos</a>), and use of Ethereum is subject to the Ethereum terms and conditions (<a href="https://ethereum.org/en/terms-of-use/" target="_blank">https://ethereum.org/en/terms-of-use/</a>). Game7 provides access to Third-Party Content and Third-Party Services as a convenience only, and such access does not constitute Game7’s approval, endorsement, or control of any such Third-Party Content or Third-Party Service. Game7 does not verify, curate, or control Third-Party Content, and does not control Third Party Services. You acknowledge sole responsibility for, and assume all risk arising from, your access to, reliance upon, or use of any Third-Party Content or Third-Party Service. Game7 disclaims all responsibility and liability for any losses on account of your reliance upon or use of such content or services. Your use of Third-Party Content and Third-Party Services through the Site is governed by these Terms and any applicable terms and conditions under which the Third-Party Content and Third-Party Services are offered. Dealing or correspondence with any third party that provides such content or services is solely between you and that third party. Game7 reserves the right to change, suspend, remove, disable, or impose access restrictions or limits on the use of any Third-Party Content or Third-Party Service at any time, without notice.
`,
            },
            {
                title: '8. Intellectual Property',
                content: 'Game7 and its licensors exclusively own all rights, title and interest in and to the Services, including all associated intellectual property rights. You acknowledge that the Services are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Services.'
            },
            {
                title: '9. General Prohibitions and Enforcement Rights',
                content: 
`
You agree that you will not violate any law, contract, intellectual property, or other third-party right, and that you are solely responsible for your conduct and content, while accessing or using the Services. You also agree that you will not:
<ul>
<li>a.	Access, tamper with, or use non-public areas of the Services, Game7 computer systems, or the technical delivery systems of Game7’s Third-Party Service providers;</li>
<li>b.	Attempt to probe, scan or test the vulnerability of any Game7 system or network, or breach any security or authentication measures;</li>
<li>c.	Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure implemented by Game7 or any of its service providers to protect the Services;</li>
<li>d.	Attempt to access or search the Services or download content from the Services using any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by Game7 or other generally available third-party web browsers;</li>
<li>e.	Attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Services;</li>
<li>f.	Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Services;</li>
<li>g.	Create, access, or use, or attempt to create, access, or use, multiple accounts or Digital Wallets to circumvent or violate these Terms, obscure your identity or location, avoid restrictions on the Services, or attempt to game, cheat, or hack any part of the Services, or gain any unfair or unauthorized advantage related to the Services;</li>
<li>h.	Collect or store any personally identifiable information from the Services from other users of the Services without their express permission;</li>
<li>i.	Engage or assist in any activity that violates any law, statute, ordinance, regulation, or sanctions program, including but not limited to the U.S. Department of Treasury’s Office of Foreign Assets Control (“<strong>OFAC</strong>”), or that involves proceeds of any unlawful activity (including but not limited to money laundering, terrorist financing or deliberately engaging in activities designed to adversely affect the performance of the Services);</li>
<li>j.	Export or re-export, directly or indirectly, the Services and/or other information or materials provided by Game7 hereunder, to any country for which the United States or any other relevant jurisdiction requires any export license or other governmental approval at the time of export without first obtaining such license or approval. In particular, but without limitation, the Services may not be exported or re-exported (a) into any U.S. embargoed countries or any country that has been designated by the U.S. Government as a “terrorist supporting” country, or (b) to anyone listed on any U.S. Government list of prohibited or restricted parties, including the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce Denied Persons List or Entity List. By using the Services, you represent and warrant that you are not located in any such country or on any such list. You are responsible for and hereby agree to comply at your sole expense with all applicable United States export laws and regulations;</li>
<li>k.	Engage in wash trading, front running, pump and dump trading, ramping, cornering, or other deceptive or manipulative trading activities while using the Services;</li>
<li>l.	Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
<li>m.	Promote or further any criminal activity or enterprise, or provide instructional information about illegal activities;</li>
<li>n.	Distribute any content that: (i) infringes, misappropriates or violates a third-party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any person or entity; or (vii) promotes illegal or harmful activities or substances;</li>
<li>o.	Use, display, mirror or frame the Services or any individual element within the Services, Game7’s name, any Game7 trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without Game7’s express written consent.</li>
</ul>
We reserve the right, but are not obligated, to remove or disable access to any content at any time and without notice, including, but not limited to, if we, at our sole discretion, consider it objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.
`
            },
            {
                title: '10. Termination',
                content: 'Game7 may suspend or terminate your access to and use of the Services, including suspending access to the Site, at our sole discretion, at any time and without notice to you. You acknowledge and agree that Game7 shall have no liability or obligation to you in such an event, and that you will not be entitled to a refund of any amounts that you have already paid to us or to any third party, to the fullest extent permitted by applicable law. Upon any termination, discontinuation or cancellation of these Terms or the Services, the following Sections will survive: 8, 9, 10, 11, 12, 13, 14, 15, 16, and 17.',            
            },
            {
                title: '11. Warranty Disclaimers',
                content: 
`
THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. GAME7 (AND ITS AFFILIATES AND SERVICE PROVIDERS) MAKE NO WARRANTY THAT THE SERVICES: (I) WILL MEET YOUR REQUIREMENTS; (II) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (III) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE. GAME7 DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AS TO THE SERVICES AND ANY CONTENT CONTAINED THEREIN.
`,          
            },
            {
                title: '12. Assumption of Risk',
                content: 
`
You accept, acknowledge and assume the following risks:
<ul>
<li>a.	By accessing and using the Services, you represent that you understand the inherent risks associated with using cryptographic and blockchain-based systems, and that you have a working knowledge of digital assets. Such systems may have vulnerabilities or other failures, or other abnormal behavior. Game7 is not responsible for any issues with the blockchain, including forks, technical node issues or any other issues that may result in the loss of funds. You acknowledge that the cost and speed of transacting with cryptographic and blockchain-based systems such as Ethereum and Arbitrum are variable and may increase at any time. You further acknowledge the risk that your digital assets may lose some or all of their value while they are supplied to or from the Services. You further acknowledge that Game7 is not responsible for any of these variables or risks and cannot be held liable for any resulting losses that you experience while accessing, using, or interacting with the Services. Accordingly, you understand and agree to assume full responsibility for all of the risks of accessing, using and interacting with the Services.</li>
<li>b.	There are risks associated with using digital assets and tokens, including but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information or assets stored within your Digital Wallet. You accept and acknowledge that Game7 will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Services, however caused.</li>
<li>c.	Game7 and its affiliates cannot control how third-party Digital Wallets and exchange platforms quote or value cryptocurrencies and other digital assets, and so Game7 expressly denies and disclaims any liability to you, and denies any obligations to indemnify or hold you harmless for any losses you may incur as a result of fluctuations in the value of cryptocurrencies or other digital assets.</li>
<li>d.	You represent that you understand that smart contracts execute automatically when certain conditions are met, and as such, typically cannot be stopped or reversed, and that vulnerabilities in smart contract programming and design, including vulnerabilities that may arise due to hacking or other security incidents, can have adverse effects to your digital assets, including but not limited to significant volatility and risk of loss.</li>
<li>e.	Certain protocols and networks require that a certain amount of Staked assets be locked for a certain Lockup Period while Staking, and Withdrawal of Staked assets may be delayed. Game7 does not guarantee the security or functionality of any Third-Party Service, including any third-party protocol, software or technology, intended to be compatible with Game7 assets.</li>
<li>f.	Game7 may rely on third-party platforms to provide the Services. If we are unable to maintain a good relationship with such platform providers; if the terms and conditions or pricing of such platform providers change; if we violate or cannot comply with the terms and conditions of such platforms; or if any of such platforms loses market share or falls out of favor or is unavailable for a prolonged period of time, access to and use of the Services may suffer.</li>
<li>g.	You are solely responsible for determining what, if any, taxes apply to your transactions. Game7 and its affiliates are not responsible for determining the taxes that apply to any such transactions. You are solely responsible for maintaining all relevant tax records and complying with any reporting requirements you may have as related to Game7 Services or Third-Party Services. You are further solely responsible for independently maintaining the accuracy of any record submitted to any tax authority including any information derived from the Services or Third-Party Services.</li>
<li>h.	The regulatory regime governing blockchain technologies, cryptocurrencies, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Services.</li>
</ul>
`
            },
            {
                title: '13. Indemnity',
                content: 
`
To the fullest extent permitted by applicable laws, you agree to indemnify, defend, and hold Game7 and its affiliates and service providers, and each of their respective officers, directors, supervisors, contractors and agents, harmless from and against any and all third-party claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way related to: (a) your access to, use of, or interaction with the Services; (b) your access to, use of, or interaction with any Third-Party Services or Third-Party Content; (c) your violation of these Terms or applicable law; (d) your violation of the rights of a third party; and (e) your negligence or willful misconduct. 
You agree to promptly notify Game7 of any such third-party claims, and to cooperate with Game7 in defending such third-party claims. You further agree that Game7 shall have the right to control the defense or settlement of any third-party claims as they relate to Game7, if Game7 so chooses. You accept and acknowledge that you may not settle or otherwise compromise any third-party claim subject to this section without Game7’s prior written consent.
`
            },
            {
                title: '14. Limitation of Liability',
                content: 
`
TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER GAME7 NOR ITS SERVICE PROVIDERS INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT GAME7 OR ITS SERVICE PROVIDERS HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
TO THE MAXIMUM EXTENT PERMITTED BY THE LAW, IN NO EVENT WILL GAME7’S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES EXCEED THE AMOUNTS YOU HAVE PAID OR ARE PAYABLE BY YOU TO GAME7 FOR USE OF THE SERVICES OR ONE HUNDRED DOLLARS ($100), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO GAME7, AS APPLICABLE.
THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN GAME7 AND YOU.
`,
            },
            {
                title: '15. Governing Law and Forum',
                content: 
`
These Terms and any action related thereto will be governed by the British Virgin Islands Arbitration Act and the laws of the British Virgin Islands, without regard to its conflict of laws provisions. Except as otherwise expressly set forth in 
16 (Dispute Resolution), the exclusive jurisdiction for all Disputes (as defined below) that you and Game7 resolve outside of arbitration will be the courts located in the British Virgin Islands, and you and Game7 each waive any objection to jurisdiction and venue in such courts.
`
            },
            {
                title: '16. Dispute Resolution',
                content: 
`
PLEASE READ THIS SECTION CAREFULLY, AS IT MAY SIGNIFICANTLY AFFECT YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT AND TO HAVE A JURY HEAR YOUR CLAIMS. IT CONTAINS PROCEDURES FOR MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.
<h3>a.	Informal Resolution of Disputes</h3>
In the event of any dispute between you and Game7 arising out of or relating to the use of the Services, these Terms, or the breach, termination, enforcement, interpretation or validity of these Terms (collectively, “<strong>Disputes</strong>”), either party must first attempt to resolve any dispute, claim or controversy informally. Accordingly, neither you nor Game7 may start a formal arbitration proceeding for at least sixty (60) days after one party notifies the other party of a claim in writing. As part of this informal resolution process, you must deliver your written notices via hand or first-class mail to us at Game7 DAO, Floor 4, Banco Popular Building, Road Town, Tortola, British Virgin Islands.
<h3>b.	Mandatory Binding Arbitration of Disputes</h3>
After the informal dispute resolution process has been exhausted, any remaining Disputes will be resolved solely by binding, individual arbitration (and not in a class, representative or consolidated action or proceeding), including threshold questions of arbitrability of any Disputes. You hereby waive your rights to a jury trial and to have any other dispute arising out of or related to these Terms and the Services, including claims related to privacy and data security resolved in court. Further, you hereby waive all rights to participate in any class action lawsuit or class wide arbitration against Game7. Instead, any dispute arising out of or related to these Terms, as well as any issue on its validity and existence, shall be referred to and finally resolved by arbitration administered by the BVI International Arbitration Centre (“<strong>BVI IAC</strong>”) in accordance with the BVI IAC Rules for the time being in force. The seat of the arbitration shall be the British Virgin Islands. The Tribunal shall consist of one (1) arbitrator, appointed by Game7. The language of the arbitration shall be English.
<h3>c.	Exceptions</h3>
As limited exceptions to Section 16(b) above: (i) both parties may seek to resolve a Dispute in small claims court in the British Virgin Islands if it qualifies; and (ii) each party retains the right to seek injunctive or other equitable relief from a court to prevent (or enjoin) the infringement or misappropriation of its intellectual property rights. Any dispute about whether a Dispute qualifies for small claims court will be resolved by that court, not by an arbitrator, in which case the arbitration proceeding will remain closed unless and until the small claims court issues a decision that the Dispute should proceed in arbitration.
<h3>d.	Class Action Waiver</h3>
All Disputes must be submitted on an individual basis. No Disputes may be arbitrated on a class or collective basis. You and Game7 expressly waive any right to submit, initiate, or participate in a representative capacity as a plaintiff, claimant or member in a class action, collective action or other representative or joint action, regardless of whether the action is filed in arbitration or in court. This provision shall survive termination of these Terms.
`
            },
            {
                title: '17. General Terms',
                content: 
`
<h3>a.	Reservation of Rights</h3>
Game7 and its licensors exclusively own all right, title, and interest in and to the Services, including all associated intellectual property rights. You acknowledge that the Services are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices incorporated in or accompanying the Services.
<h3>b.	Entire Agreement</h3>
These Terms constitute the entire and exclusive understanding and agreement between Game7 and you regarding the Services, and these Terms supersede and replace all prior oral or written understandings or agreements between Game7 and you regarding the Services. If any provision of these Terms is held invalid or unenforceable by an arbitrator or a court of competent jurisdiction, that provision will be enforced to the maximum extent permissible, and the other provisions of these Terms will remain in full force and effect. Except where provided by applicable law in your jurisdiction, you may not assign or transfer these Terms, by operation of law or otherwise, without Game7’s prior written consent. Any attempt by you to assign or transfer these Terms absent our consent or your statutory right, without such consent, will be null and void in its entirety. Game7 may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors, and permitted assigns.
<h3>c.	Notices</h3>
Any notices or other communications provided by Game7 under these Terms will be given: (i) via email; or (ii) by posting to the Services. For notices made by email, the date of receipt will be deemed the date on which such notice is transmitted.
<h3>d.	Waiver of Rights</h3>
Game7’s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Game7. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.
`
            },
            {
                title: '18. Contact Game7',
                content: 'If you have any questions about these Terms or the Services, please contact <a href="mailto:info@game7.io">info@game7.io</a>.'
            },
        ]
    },
    cookie: {
        title: 'Cookie Policy',
        lastUpdated: 'June 1st, 2023',
        sections: [
            {
                title: 'First',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Second',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Third',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Fourth',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Fifth',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
        ]
    },
    privacy: {
        title: 'Privacy Policy',
        lastUpdated: 'June 1st, 2023',
        sections: [
            {
                title: 'First',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Second',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Third',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Fourth',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
            {
                title: 'Fifth',
                content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. '
            },
        ]
    }
}