// This file was generated by seer: https://github.com/moonstream-to/seer.
// seer version: 0.1.20
// seer command: seer evm generate --package TokenSender --cli --struct TokenSender --output bindings/TokenSender/TokenSender.go
// Code generated - DO NOT EDIT.
// This file is a generated binding and any manual changes will be lost.

package TokenSender

import (
	"errors"
	"math/big"
	"strings"

	"context"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"

	// Reference imports to suppress errors if they are not otherwise used.
	"encoding/hex"
	"fmt"
	"os"
	"time"

	"github.com/ethereum/go-ethereum/accounts/keystore"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/spf13/cobra"
	"golang.org/x/term"
)

var (
	_ = errors.New
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
	_ = abi.ConvertType
)

// TokenSenderMetaData contains all meta data concerning the TokenSender contract.
var TokenSenderMetaData = &bind.MetaData{
	ABI: "[{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"_faucetTimeInterval\",\"type\":\"uint256\"}],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"recipient\",\"type\":\"address\"}],\"name\":\"TokenSenderClaimIntervalNotPassed\",\"type\":\"error\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":true,\"internalType\":\"address\",\"name\":\"sender\",\"type\":\"address\"},{\"indexed\":true,\"internalType\":\"address\",\"name\":\"recipient\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"uint256\",\"name\":\"amount\",\"type\":\"uint256\"}],\"name\":\"TokensSent\",\"type\":\"event\"},{\"inputs\":[],\"name\":\"faucetTimeInterval\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\"}],\"name\":\"lastSentTimestamp\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"recipient\",\"type\":\"address\"}],\"name\":\"send\",\"outputs\":[],\"stateMutability\":\"payable\",\"type\":\"function\"}]",
	Bin: "0x608060405234801561001057600080fd5b506040516102de3803806102de83398101604081905261002f91610037565b600055610050565b60006020828403121561004957600080fd5b5051919050565b61027f8061005f6000396000f3fe6080604052600436106100345760003560e01c80631aa23f48146100395780633e58c58c14610078578063a42532ad1461008d575b600080fd5b34801561004557600080fd5b506100666100543660046101cc565b60016020526000908152604090205481565b60405190815260200160405180910390f35b61008b6100863660046101cc565b6100a3565b005b34801561009957600080fd5b5061006660005481565b6000805473ffffffffffffffffffffffffffffffffffffffff8316825260016020526040909120546100d59190610209565b4211610129576040517f12bf079900000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff8216600482015260240160405180910390fd5b73ffffffffffffffffffffffffffffffffffffffff8116600081815260016020526040808220429055513480156108fc0292909190818181858888f1935050505015801561017b573d6000803e3d6000fd5b5060405134815273ffffffffffffffffffffffffffffffffffffffff82169033907fe607861baff3d292b19188affe88c1a72bdcb69d3015f18bb2cd0bf5349cc3e19060200160405180910390a350565b6000602082840312156101de57600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461020257600080fd5b9392505050565b80820180821115610243577f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b9291505056fea2646970667358221220703a3e864c2dd78d0d7cb300fb76b4ebf7183102843c873f59f80daa1132d01d64736f6c63430008180033",
}

// TokenSenderABI is the input ABI used to generate the binding from.
// Deprecated: Use TokenSenderMetaData.ABI instead.
var TokenSenderABI = TokenSenderMetaData.ABI

// TokenSenderBin is the compiled bytecode used for deploying new contracts.
// Deprecated: Use TokenSenderMetaData.Bin instead.
var TokenSenderBin = TokenSenderMetaData.Bin

// DeployTokenSender deploys a new Ethereum contract, binding an instance of TokenSender to it.
func DeployTokenSender(auth *bind.TransactOpts, backend bind.ContractBackend, _faucetTimeInterval *big.Int) (common.Address, *types.Transaction, *TokenSender, error) {
	parsed, err := TokenSenderMetaData.GetAbi()
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	if parsed == nil {
		return common.Address{}, nil, nil, errors.New("GetABI returned nil")
	}

	address, tx, contract, err := bind.DeployContract(auth, *parsed, common.FromHex(TokenSenderBin), backend, _faucetTimeInterval)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	return address, tx, &TokenSender{TokenSenderCaller: TokenSenderCaller{contract: contract}, TokenSenderTransactor: TokenSenderTransactor{contract: contract}, TokenSenderFilterer: TokenSenderFilterer{contract: contract}}, nil
}

// TokenSender is an auto generated Go binding around an Ethereum contract.
type TokenSender struct {
	TokenSenderCaller     // Read-only binding to the contract
	TokenSenderTransactor // Write-only binding to the contract
	TokenSenderFilterer   // Log filterer for contract events
}

// TokenSenderCaller is an auto generated read-only Go binding around an Ethereum contract.
type TokenSenderCaller struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// TokenSenderTransactor is an auto generated write-only Go binding around an Ethereum contract.
type TokenSenderTransactor struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// TokenSenderFilterer is an auto generated log filtering Go binding around an Ethereum contract events.
type TokenSenderFilterer struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// TokenSenderSession is an auto generated Go binding around an Ethereum contract,
// with pre-set call and transact options.
type TokenSenderSession struct {
	Contract     *TokenSender      // Generic contract binding to set the session for
	CallOpts     bind.CallOpts     // Call options to use throughout this session
	TransactOpts bind.TransactOpts // Transaction auth options to use throughout this session
}

// TokenSenderCallerSession is an auto generated read-only Go binding around an Ethereum contract,
// with pre-set call options.
type TokenSenderCallerSession struct {
	Contract *TokenSenderCaller // Generic contract caller binding to set the session for
	CallOpts bind.CallOpts      // Call options to use throughout this session
}

// TokenSenderTransactorSession is an auto generated write-only Go binding around an Ethereum contract,
// with pre-set transact options.
type TokenSenderTransactorSession struct {
	Contract     *TokenSenderTransactor // Generic contract transactor binding to set the session for
	TransactOpts bind.TransactOpts      // Transaction auth options to use throughout this session
}

// TokenSenderRaw is an auto generated low-level Go binding around an Ethereum contract.
type TokenSenderRaw struct {
	Contract *TokenSender // Generic contract binding to access the raw methods on
}

// TokenSenderCallerRaw is an auto generated low-level read-only Go binding around an Ethereum contract.
type TokenSenderCallerRaw struct {
	Contract *TokenSenderCaller // Generic read-only contract binding to access the raw methods on
}

// TokenSenderTransactorRaw is an auto generated low-level write-only Go binding around an Ethereum contract.
type TokenSenderTransactorRaw struct {
	Contract *TokenSenderTransactor // Generic write-only contract binding to access the raw methods on
}

// NewTokenSender creates a new instance of TokenSender, bound to a specific deployed contract.
func NewTokenSender(address common.Address, backend bind.ContractBackend) (*TokenSender, error) {
	contract, err := bindTokenSender(address, backend, backend, backend)
	if err != nil {
		return nil, err
	}
	return &TokenSender{TokenSenderCaller: TokenSenderCaller{contract: contract}, TokenSenderTransactor: TokenSenderTransactor{contract: contract}, TokenSenderFilterer: TokenSenderFilterer{contract: contract}}, nil
}

// NewTokenSenderCaller creates a new read-only instance of TokenSender, bound to a specific deployed contract.
func NewTokenSenderCaller(address common.Address, caller bind.ContractCaller) (*TokenSenderCaller, error) {
	contract, err := bindTokenSender(address, caller, nil, nil)
	if err != nil {
		return nil, err
	}
	return &TokenSenderCaller{contract: contract}, nil
}

// NewTokenSenderTransactor creates a new write-only instance of TokenSender, bound to a specific deployed contract.
func NewTokenSenderTransactor(address common.Address, transactor bind.ContractTransactor) (*TokenSenderTransactor, error) {
	contract, err := bindTokenSender(address, nil, transactor, nil)
	if err != nil {
		return nil, err
	}
	return &TokenSenderTransactor{contract: contract}, nil
}

// NewTokenSenderFilterer creates a new log filterer instance of TokenSender, bound to a specific deployed contract.
func NewTokenSenderFilterer(address common.Address, filterer bind.ContractFilterer) (*TokenSenderFilterer, error) {
	contract, err := bindTokenSender(address, nil, nil, filterer)
	if err != nil {
		return nil, err
	}
	return &TokenSenderFilterer{contract: contract}, nil
}

// bindTokenSender binds a generic wrapper to an already deployed contract.
func bindTokenSender(address common.Address, caller bind.ContractCaller, transactor bind.ContractTransactor, filterer bind.ContractFilterer) (*bind.BoundContract, error) {
	parsed, err := TokenSenderMetaData.GetAbi()
	if err != nil {
		return nil, err
	}
	return bind.NewBoundContract(address, *parsed, caller, transactor, filterer), nil
}

// Call invokes the (constant) contract method with params as input values and
// sets the output to result. The result type might be a single field for simple
// returns, a slice of interfaces for anonymous returns and a struct for named
// returns.
func (_TokenSender *TokenSenderRaw) Call(opts *bind.CallOpts, result *[]interface{}, method string, params ...interface{}) error {
	return _TokenSender.Contract.TokenSenderCaller.contract.Call(opts, result, method, params...)
}

// Transfer initiates a plain transaction to move funds to the contract, calling
// its default method if one is available.
func (_TokenSender *TokenSenderRaw) Transfer(opts *bind.TransactOpts) (*types.Transaction, error) {
	return _TokenSender.Contract.TokenSenderTransactor.contract.Transfer(opts)
}

// Transact invokes the (paid) contract method with params as input values.
func (_TokenSender *TokenSenderRaw) Transact(opts *bind.TransactOpts, method string, params ...interface{}) (*types.Transaction, error) {
	return _TokenSender.Contract.TokenSenderTransactor.contract.Transact(opts, method, params...)
}

// Call invokes the (constant) contract method with params as input values and
// sets the output to result. The result type might be a single field for simple
// returns, a slice of interfaces for anonymous returns and a struct for named
// returns.
func (_TokenSender *TokenSenderCallerRaw) Call(opts *bind.CallOpts, result *[]interface{}, method string, params ...interface{}) error {
	return _TokenSender.Contract.contract.Call(opts, result, method, params...)
}

// Transfer initiates a plain transaction to move funds to the contract, calling
// its default method if one is available.
func (_TokenSender *TokenSenderTransactorRaw) Transfer(opts *bind.TransactOpts) (*types.Transaction, error) {
	return _TokenSender.Contract.contract.Transfer(opts)
}

// Transact invokes the (paid) contract method with params as input values.
func (_TokenSender *TokenSenderTransactorRaw) Transact(opts *bind.TransactOpts, method string, params ...interface{}) (*types.Transaction, error) {
	return _TokenSender.Contract.contract.Transact(opts, method, params...)
}

// FaucetTimeInterval is a free data retrieval call binding the contract method 0xa42532ad.
//
// Solidity: function faucetTimeInterval() view returns(uint256)
func (_TokenSender *TokenSenderCaller) FaucetTimeInterval(opts *bind.CallOpts) (*big.Int, error) {
	var out []interface{}
	err := _TokenSender.contract.Call(opts, &out, "faucetTimeInterval")

	if err != nil {
		return *new(*big.Int), err
	}

	out0 := *abi.ConvertType(out[0], new(*big.Int)).(**big.Int)

	return out0, err

}

// FaucetTimeInterval is a free data retrieval call binding the contract method 0xa42532ad.
//
// Solidity: function faucetTimeInterval() view returns(uint256)
func (_TokenSender *TokenSenderSession) FaucetTimeInterval() (*big.Int, error) {
	return _TokenSender.Contract.FaucetTimeInterval(&_TokenSender.CallOpts)
}

// FaucetTimeInterval is a free data retrieval call binding the contract method 0xa42532ad.
//
// Solidity: function faucetTimeInterval() view returns(uint256)
func (_TokenSender *TokenSenderCallerSession) FaucetTimeInterval() (*big.Int, error) {
	return _TokenSender.Contract.FaucetTimeInterval(&_TokenSender.CallOpts)
}

// LastSentTimestamp is a free data retrieval call binding the contract method 0x1aa23f48.
//
// Solidity: function lastSentTimestamp(address ) view returns(uint256)
func (_TokenSender *TokenSenderCaller) LastSentTimestamp(opts *bind.CallOpts, arg0 common.Address) (*big.Int, error) {
	var out []interface{}
	err := _TokenSender.contract.Call(opts, &out, "lastSentTimestamp", arg0)

	if err != nil {
		return *new(*big.Int), err
	}

	out0 := *abi.ConvertType(out[0], new(*big.Int)).(**big.Int)

	return out0, err

}

// LastSentTimestamp is a free data retrieval call binding the contract method 0x1aa23f48.
//
// Solidity: function lastSentTimestamp(address ) view returns(uint256)
func (_TokenSender *TokenSenderSession) LastSentTimestamp(arg0 common.Address) (*big.Int, error) {
	return _TokenSender.Contract.LastSentTimestamp(&_TokenSender.CallOpts, arg0)
}

// LastSentTimestamp is a free data retrieval call binding the contract method 0x1aa23f48.
//
// Solidity: function lastSentTimestamp(address ) view returns(uint256)
func (_TokenSender *TokenSenderCallerSession) LastSentTimestamp(arg0 common.Address) (*big.Int, error) {
	return _TokenSender.Contract.LastSentTimestamp(&_TokenSender.CallOpts, arg0)
}

// Send is a paid mutator transaction binding the contract method 0x3e58c58c.
//
// Solidity: function send(address recipient) payable returns()
func (_TokenSender *TokenSenderTransactor) Send(opts *bind.TransactOpts, recipient common.Address) (*types.Transaction, error) {
	return _TokenSender.contract.Transact(opts, "send", recipient)
}

// Send is a paid mutator transaction binding the contract method 0x3e58c58c.
//
// Solidity: function send(address recipient) payable returns()
func (_TokenSender *TokenSenderSession) Send(recipient common.Address) (*types.Transaction, error) {
	return _TokenSender.Contract.Send(&_TokenSender.TransactOpts, recipient)
}

// Send is a paid mutator transaction binding the contract method 0x3e58c58c.
//
// Solidity: function send(address recipient) payable returns()
func (_TokenSender *TokenSenderTransactorSession) Send(recipient common.Address) (*types.Transaction, error) {
	return _TokenSender.Contract.Send(&_TokenSender.TransactOpts, recipient)
}

// TokenSenderTokensSentIterator is returned from FilterTokensSent and is used to iterate over the raw logs and unpacked data for TokensSent events raised by the TokenSender contract.
type TokenSenderTokensSentIterator struct {
	Event *TokenSenderTokensSent // Event containing the contract specifics and raw log

	contract *bind.BoundContract // Generic contract to use for unpacking event data
	event    string              // Event name to use for unpacking event data

	logs chan types.Log        // Log channel receiving the found contract events
	sub  ethereum.Subscription // Subscription for errors, completion and termination
	done bool                  // Whether the subscription completed delivering logs
	fail error                 // Occurred error to stop iteration
}

// Next advances the iterator to the subsequent event, returning whether there
// are any more events found. In case of a retrieval or parsing error, false is
// returned and Error() can be queried for the exact failure.
func (it *TokenSenderTokensSentIterator) Next() bool {
	// If the iterator failed, stop iterating
	if it.fail != nil {
		return false
	}
	// If the iterator completed, deliver directly whatever's available
	if it.done {
		select {
		case log := <-it.logs:
			it.Event = new(TokenSenderTokensSent)
			if err := it.contract.UnpackLog(it.Event, it.event, log); err != nil {
				it.fail = err
				return false
			}
			it.Event.Raw = log
			return true

		default:
			return false
		}
	}
	// Iterator still in progress, wait for either a data or an error event
	select {
	case log := <-it.logs:
		it.Event = new(TokenSenderTokensSent)
		if err := it.contract.UnpackLog(it.Event, it.event, log); err != nil {
			it.fail = err
			return false
		}
		it.Event.Raw = log
		return true

	case err := <-it.sub.Err():
		it.done = true
		it.fail = err
		return it.Next()
	}
}

// Error returns any retrieval or parsing error occurred during filtering.
func (it *TokenSenderTokensSentIterator) Error() error {
	return it.fail
}

// Close terminates the iteration process, releasing any pending underlying
// resources.
func (it *TokenSenderTokensSentIterator) Close() error {
	it.sub.Unsubscribe()
	return nil
}

// TokenSenderTokensSent represents a TokensSent event raised by the TokenSender contract.
type TokenSenderTokensSent struct {
	Sender    common.Address
	Recipient common.Address
	Amount    *big.Int
	Raw       types.Log // Blockchain specific contextual infos
}

// FilterTokensSent is a free log retrieval operation binding the contract event 0xe607861baff3d292b19188affe88c1a72bdcb69d3015f18bb2cd0bf5349cc3e1.
//
// Solidity: event TokensSent(address indexed sender, address indexed recipient, uint256 amount)
func (_TokenSender *TokenSenderFilterer) FilterTokensSent(opts *bind.FilterOpts, sender []common.Address, recipient []common.Address) (*TokenSenderTokensSentIterator, error) {

	var senderRule []interface{}
	for _, senderItem := range sender {
		senderRule = append(senderRule, senderItem)
	}
	var recipientRule []interface{}
	for _, recipientItem := range recipient {
		recipientRule = append(recipientRule, recipientItem)
	}

	logs, sub, err := _TokenSender.contract.FilterLogs(opts, "TokensSent", senderRule, recipientRule)
	if err != nil {
		return nil, err
	}
	return &TokenSenderTokensSentIterator{contract: _TokenSender.contract, event: "TokensSent", logs: logs, sub: sub}, nil
}

// WatchTokensSent is a free log subscription operation binding the contract event 0xe607861baff3d292b19188affe88c1a72bdcb69d3015f18bb2cd0bf5349cc3e1.
//
// Solidity: event TokensSent(address indexed sender, address indexed recipient, uint256 amount)
func (_TokenSender *TokenSenderFilterer) WatchTokensSent(opts *bind.WatchOpts, sink chan<- *TokenSenderTokensSent, sender []common.Address, recipient []common.Address) (event.Subscription, error) {

	var senderRule []interface{}
	for _, senderItem := range sender {
		senderRule = append(senderRule, senderItem)
	}
	var recipientRule []interface{}
	for _, recipientItem := range recipient {
		recipientRule = append(recipientRule, recipientItem)
	}

	logs, sub, err := _TokenSender.contract.WatchLogs(opts, "TokensSent", senderRule, recipientRule)
	if err != nil {
		return nil, err
	}
	return event.NewSubscription(func(quit <-chan struct{}) error {
		defer sub.Unsubscribe()
		for {
			select {
			case log := <-logs:
				// New log arrived, parse the event and forward to the user
				event := new(TokenSenderTokensSent)
				if err := _TokenSender.contract.UnpackLog(event, "TokensSent", log); err != nil {
					return err
				}
				event.Raw = log

				select {
				case sink <- event:
				case err := <-sub.Err():
					return err
				case <-quit:
					return nil
				}
			case err := <-sub.Err():
				return err
			case <-quit:
				return nil
			}
		}
	}), nil
}

// ParseTokensSent is a log parse operation binding the contract event 0xe607861baff3d292b19188affe88c1a72bdcb69d3015f18bb2cd0bf5349cc3e1.
//
// Solidity: event TokensSent(address indexed sender, address indexed recipient, uint256 amount)
func (_TokenSender *TokenSenderFilterer) ParseTokensSent(log types.Log) (*TokenSenderTokensSent, error) {
	event := new(TokenSenderTokensSent)
	if err := _TokenSender.contract.UnpackLog(event, "TokensSent", log); err != nil {
		return nil, err
	}
	event.Raw = log
	return event, nil
}

func CreateTokenSenderDeploymentCommand() *cobra.Command {
	var keyfile, nonce, password, value, gasPrice, maxFeePerGas, maxPriorityFeePerGas, rpc string
	var gasLimit uint64
	var simulate bool
	var timeout uint

	var faucetTimeInterval *big.Int
	var faucetTimeIntervalRaw string

	cmd := &cobra.Command{
		Use:   "deploy",
		Short: "Deploy a new TokenSender contract",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if keyfile == "" {
				return fmt.Errorf("--keystore not specified (this should be a path to an Ethereum account keystore file)")
			}

			if faucetTimeIntervalRaw == "" {
				return fmt.Errorf("--faucet-time-interval argument not specified")
			}
			faucetTimeInterval = new(big.Int)
			faucetTimeInterval.SetString(faucetTimeIntervalRaw, 0)

			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			client, clientErr := NewClient(rpc)
			if clientErr != nil {
				return clientErr
			}

			key, keyErr := KeyFromFile(keyfile, password)
			if keyErr != nil {
				return keyErr
			}

			chainIDCtx, cancelChainIDCtx := NewChainContext(timeout)
			defer cancelChainIDCtx()
			chainID, chainIDErr := client.ChainID(chainIDCtx)
			if chainIDErr != nil {
				return chainIDErr
			}

			transactionOpts, transactionOptsErr := bind.NewKeyedTransactorWithChainID(key.PrivateKey, chainID)
			if transactionOptsErr != nil {
				return transactionOptsErr
			}

			SetTransactionParametersFromArgs(transactionOpts, nonce, value, gasPrice, maxFeePerGas, maxPriorityFeePerGas, gasLimit, simulate)

			address, deploymentTransaction, _, deploymentErr := DeployTokenSender(
				transactionOpts,
				client,
				faucetTimeInterval,
			)
			if deploymentErr != nil {
				return deploymentErr
			}

			cmd.Printf("Transaction hash: %s\nContract address: %s\n", deploymentTransaction.Hash().Hex(), address.Hex())
			if transactionOpts.NoSend {
				estimationMessage := ethereum.CallMsg{
					From: transactionOpts.From,
					Data: deploymentTransaction.Data(),
				}

				gasEstimationCtx, cancelGasEstimationCtx := NewChainContext(timeout)
				defer cancelGasEstimationCtx()

				gasEstimate, gasEstimateErr := client.EstimateGas(gasEstimationCtx, estimationMessage)
				if gasEstimateErr != nil {
					return gasEstimateErr
				}

				transactionBinary, transactionBinaryErr := deploymentTransaction.MarshalBinary()
				if transactionBinaryErr != nil {
					return transactionBinaryErr
				}
				transactionBinaryHex := hex.EncodeToString(transactionBinary)

				cmd.Printf("Transaction: %s\nEstimated gas: %d\n", transactionBinaryHex, gasEstimate)
			} else {
				cmd.Println("Transaction submitted")
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&rpc, "rpc", "", "URL of the JSONRPC API to use")
	cmd.Flags().StringVar(&keyfile, "keyfile", "", "Path to the keystore file to use for the transaction")
	cmd.Flags().StringVar(&password, "password", "", "Password to use to unlock the keystore (if not specified, you will be prompted for the password when the command executes)")
	cmd.Flags().StringVar(&nonce, "nonce", "", "Nonce to use for the transaction")
	cmd.Flags().StringVar(&value, "value", "", "Value to send with the transaction")
	cmd.Flags().StringVar(&gasPrice, "gas-price", "", "Gas price to use for the transaction")
	cmd.Flags().StringVar(&maxFeePerGas, "max-fee-per-gas", "", "Maximum fee per gas to use for the (EIP-1559) transaction")
	cmd.Flags().StringVar(&maxPriorityFeePerGas, "max-priority-fee-per-gas", "", "Maximum priority fee per gas to use for the (EIP-1559) transaction")
	cmd.Flags().Uint64Var(&gasLimit, "gas-limit", 0, "Gas limit for the transaction")
	cmd.Flags().BoolVar(&simulate, "simulate", false, "Simulate the transaction without sending it")
	cmd.Flags().UintVar(&timeout, "timeout", 60, "Timeout (in seconds) for interactions with the JSONRPC API")

	cmd.Flags().StringVar(&faucetTimeIntervalRaw, "faucet-time-interval", "", "faucet-time-interval argument")

	return cmd
}

func CreateFaucetTimeIntervalCommand() *cobra.Command {
	var contractAddressRaw, rpc string
	var contractAddress common.Address
	var timeout uint

	var blockNumberRaw, fromAddressRaw string
	var pending bool

	var capture0 *big.Int

	cmd := &cobra.Command{
		Use:   "faucet-time-interval",
		Short: "Call the FaucetTimeInterval view method on a TokenSender contract",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if contractAddressRaw == "" {
				return fmt.Errorf("--contract not specified")
			} else if !common.IsHexAddress(contractAddressRaw) {
				return fmt.Errorf("--contract is not a valid Ethereum address")
			}
			contractAddress = common.HexToAddress(contractAddressRaw)

			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			client, clientErr := NewClient(rpc)
			if clientErr != nil {
				return clientErr
			}

			contract, contractErr := NewTokenSender(contractAddress, client)
			if contractErr != nil {
				return contractErr
			}

			callOpts := bind.CallOpts{}
			SetCallParametersFromArgs(&callOpts, pending, fromAddressRaw, blockNumberRaw)

			session := TokenSenderCallerSession{
				Contract: &contract.TokenSenderCaller,
				CallOpts: callOpts,
			}

			var callErr error
			capture0, callErr = session.FaucetTimeInterval()
			if callErr != nil {
				return callErr
			}

			cmd.Printf("0: %s\n", capture0.String())

			return nil
		},
	}

	cmd.Flags().StringVar(&rpc, "rpc", "", "URL of the JSONRPC API to use")
	cmd.Flags().StringVar(&blockNumberRaw, "block", "", "Block number at which to call the view method")
	cmd.Flags().BoolVar(&pending, "pending", false, "Set this flag if it's ok to call the view method against pending state")
	cmd.Flags().UintVar(&timeout, "timeout", 60, "Timeout (in seconds) for interactions with the JSONRPC API")
	cmd.Flags().StringVar(&contractAddressRaw, "contract", "", "Address of the contract to interact with")
	cmd.Flags().StringVar(&fromAddressRaw, "from", "", "Optional address for caller of the view method")

	return cmd
}
func CreateLastSentTimestampCommand() *cobra.Command {
	var contractAddressRaw, rpc string
	var contractAddress common.Address
	var timeout uint

	var blockNumberRaw, fromAddressRaw string
	var pending bool

	var arg0 common.Address
	var arg0Raw string

	var capture0 *big.Int

	cmd := &cobra.Command{
		Use:   "last-sent-timestamp",
		Short: "Call the LastSentTimestamp view method on a TokenSender contract",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if contractAddressRaw == "" {
				return fmt.Errorf("--contract not specified")
			} else if !common.IsHexAddress(contractAddressRaw) {
				return fmt.Errorf("--contract is not a valid Ethereum address")
			}
			contractAddress = common.HexToAddress(contractAddressRaw)

			if arg0Raw == "" {
				return fmt.Errorf("--arg-0 argument not specified")
			} else if !common.IsHexAddress(arg0Raw) {
				return fmt.Errorf("--arg-0 argument is not a valid Ethereum address")
			}
			arg0 = common.HexToAddress(arg0Raw)

			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			client, clientErr := NewClient(rpc)
			if clientErr != nil {
				return clientErr
			}

			contract, contractErr := NewTokenSender(contractAddress, client)
			if contractErr != nil {
				return contractErr
			}

			callOpts := bind.CallOpts{}
			SetCallParametersFromArgs(&callOpts, pending, fromAddressRaw, blockNumberRaw)

			session := TokenSenderCallerSession{
				Contract: &contract.TokenSenderCaller,
				CallOpts: callOpts,
			}

			var callErr error
			capture0, callErr = session.LastSentTimestamp(
				arg0,
			)
			if callErr != nil {
				return callErr
			}

			cmd.Printf("0: %s\n", capture0.String())

			return nil
		},
	}

	cmd.Flags().StringVar(&rpc, "rpc", "", "URL of the JSONRPC API to use")
	cmd.Flags().StringVar(&blockNumberRaw, "block", "", "Block number at which to call the view method")
	cmd.Flags().BoolVar(&pending, "pending", false, "Set this flag if it's ok to call the view method against pending state")
	cmd.Flags().UintVar(&timeout, "timeout", 60, "Timeout (in seconds) for interactions with the JSONRPC API")
	cmd.Flags().StringVar(&contractAddressRaw, "contract", "", "Address of the contract to interact with")
	cmd.Flags().StringVar(&fromAddressRaw, "from", "", "Optional address for caller of the view method")

	cmd.Flags().StringVar(&arg0Raw, "arg-0", "", "arg-0 argument (common.Address)")

	return cmd
}

func CreateSendCommand() *cobra.Command {
	var keyfile, nonce, password, value, gasPrice, maxFeePerGas, maxPriorityFeePerGas, rpc, contractAddressRaw string
	var gasLimit uint64
	var simulate bool
	var timeout uint
	var contractAddress common.Address

	var recipient common.Address
	var recipientRaw string

	cmd := &cobra.Command{
		Use:   "send",
		Short: "Execute the Send method on a TokenSender contract",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if keyfile == "" {
				return fmt.Errorf("--keystore not specified")
			}

			if contractAddressRaw == "" {
				return fmt.Errorf("--contract not specified")
			} else if !common.IsHexAddress(contractAddressRaw) {
				return fmt.Errorf("--contract is not a valid Ethereum address")
			}
			contractAddress = common.HexToAddress(contractAddressRaw)

			if recipientRaw == "" {
				return fmt.Errorf("--recipient argument not specified")
			} else if !common.IsHexAddress(recipientRaw) {
				return fmt.Errorf("--recipient argument is not a valid Ethereum address")
			}
			recipient = common.HexToAddress(recipientRaw)

			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			client, clientErr := NewClient(rpc)
			if clientErr != nil {
				return clientErr
			}

			key, keyErr := KeyFromFile(keyfile, password)
			if keyErr != nil {
				return keyErr
			}

			chainIDCtx, cancelChainIDCtx := NewChainContext(timeout)
			defer cancelChainIDCtx()
			chainID, chainIDErr := client.ChainID(chainIDCtx)
			if chainIDErr != nil {
				return chainIDErr
			}

			transactionOpts, transactionOptsErr := bind.NewKeyedTransactorWithChainID(key.PrivateKey, chainID)
			if transactionOptsErr != nil {
				return transactionOptsErr
			}

			SetTransactionParametersFromArgs(transactionOpts, nonce, value, gasPrice, maxFeePerGas, maxPriorityFeePerGas, gasLimit, simulate)

			contract, contractErr := NewTokenSender(contractAddress, client)
			if contractErr != nil {
				return contractErr
			}

			session := TokenSenderTransactorSession{
				Contract:     &contract.TokenSenderTransactor,
				TransactOpts: *transactionOpts,
			}

			transaction, transactionErr := session.Send(
				recipient,
			)
			if transactionErr != nil {
				return transactionErr
			}

			cmd.Printf("Transaction hash: %s\n", transaction.Hash().Hex())
			if transactionOpts.NoSend {
				estimationMessage := ethereum.CallMsg{
					From: transactionOpts.From,
					To:   &contractAddress,
					Data: transaction.Data(),
				}

				gasEstimationCtx, cancelGasEstimationCtx := NewChainContext(timeout)
				defer cancelGasEstimationCtx()

				gasEstimate, gasEstimateErr := client.EstimateGas(gasEstimationCtx, estimationMessage)
				if gasEstimateErr != nil {
					return gasEstimateErr
				}

				transactionBinary, transactionBinaryErr := transaction.MarshalBinary()
				if transactionBinaryErr != nil {
					return transactionBinaryErr
				}
				transactionBinaryHex := hex.EncodeToString(transactionBinary)

				cmd.Printf("Transaction: %s\nEstimated gas: %d\n", transactionBinaryHex, gasEstimate)
			} else {
				cmd.Println("Transaction submitted")
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&rpc, "rpc", "", "URL of the JSONRPC API to use")
	cmd.Flags().StringVar(&keyfile, "keyfile", "", "Path to the keystore file to use for the transaction")
	cmd.Flags().StringVar(&password, "password", "", "Password to use to unlock the keystore (if not specified, you will be prompted for the password when the command executes)")
	cmd.Flags().StringVar(&nonce, "nonce", "", "Nonce to use for the transaction")
	cmd.Flags().StringVar(&value, "value", "", "Value to send with the transaction")
	cmd.Flags().StringVar(&gasPrice, "gas-price", "", "Gas price to use for the transaction")
	cmd.Flags().StringVar(&maxFeePerGas, "max-fee-per-gas", "", "Maximum fee per gas to use for the (EIP-1559) transaction")
	cmd.Flags().StringVar(&maxPriorityFeePerGas, "max-priority-fee-per-gas", "", "Maximum priority fee per gas to use for the (EIP-1559) transaction")
	cmd.Flags().Uint64Var(&gasLimit, "gas-limit", 0, "Gas limit for the transaction")
	cmd.Flags().BoolVar(&simulate, "simulate", false, "Simulate the transaction without sending it")
	cmd.Flags().UintVar(&timeout, "timeout", 60, "Timeout (in seconds) for interactions with the JSONRPC API")
	cmd.Flags().StringVar(&contractAddressRaw, "contract", "", "Address of the contract to interact with")

	cmd.Flags().StringVar(&recipientRaw, "recipient", "", "recipient argument (common.Address)")

	return cmd
}

var ErrNoRPCURL error = errors.New("no RPC URL provided -- please pass an RPC URL from the command line or set the TOKEN_SENDER_RPC_URL environment variable")

// Generates an Ethereum client to the JSONRPC API at the given URL. If rpcURL is empty, then it
// attempts to read the RPC URL from the TOKEN_SENDER_RPC_URL environment variable. If that is empty,
// too, then it returns an error.
func NewClient(rpcURL string) (*ethclient.Client, error) {
	if rpcURL == "" {
		rpcURL = os.Getenv("TOKEN_SENDER_RPC_URL")
	}

	if rpcURL == "" {
		return nil, ErrNoRPCURL
	}

	client, err := ethclient.Dial(rpcURL)
	return client, err
}

// Creates a new context to be used when interacting with the chain client.
func NewChainContext(timeout uint) (context.Context, context.CancelFunc) {
	baseCtx := context.Background()
	parsedTimeout := time.Duration(timeout) * time.Second
	ctx, cancel := context.WithTimeout(baseCtx, parsedTimeout)
	return ctx, cancel
}

// Unlocks a key from a keystore (byte contents of a keystore file) with the given password.
func UnlockKeystore(keystoreData []byte, password string) (*keystore.Key, error) {
	key, err := keystore.DecryptKey(keystoreData, password)
	return key, err
}

// Loads a key from file, prompting the user for the password if it is not provided as a function argument.
func KeyFromFile(keystoreFile string, password string) (*keystore.Key, error) {
	var emptyKey *keystore.Key
	keystoreContent, readErr := os.ReadFile(keystoreFile)
	if readErr != nil {
		return emptyKey, readErr
	}

	// If password is "", prompt user for password.
	if password == "" {
		fmt.Printf("Please provide a password for keystore (%s): ", keystoreFile)
		passwordRaw, inputErr := term.ReadPassword(int(os.Stdin.Fd()))
		if inputErr != nil {
			return emptyKey, fmt.Errorf("error reading password: %s", inputErr.Error())
		}
		fmt.Print("\n")
		password = string(passwordRaw)
	}

	key, err := UnlockKeystore(keystoreContent, password)
	return key, err
}

// This method is used to set the parameters on a view call from command line arguments (represented mostly as
// strings).
func SetCallParametersFromArgs(opts *bind.CallOpts, pending bool, fromAddress, blockNumber string) {
	if pending {
		opts.Pending = true
	}

	if fromAddress != "" {
		opts.From = common.HexToAddress(fromAddress)
	}

	if blockNumber != "" {
		opts.BlockNumber = new(big.Int)
		opts.BlockNumber.SetString(blockNumber, 0)
	}
}

// This method is used to set the parameters on a transaction from command line arguments (represented mostly as
// strings).
func SetTransactionParametersFromArgs(opts *bind.TransactOpts, nonce, value, gasPrice, maxFeePerGas, maxPriorityFeePerGas string, gasLimit uint64, noSend bool) {
	if nonce != "" {
		opts.Nonce = new(big.Int)
		opts.Nonce.SetString(nonce, 0)
	}

	if value != "" {
		opts.Value = new(big.Int)
		opts.Value.SetString(value, 0)
	}

	if gasPrice != "" {
		opts.GasPrice = new(big.Int)
		opts.GasPrice.SetString(gasPrice, 0)
	}

	if maxFeePerGas != "" {
		opts.GasFeeCap = new(big.Int)
		opts.GasFeeCap.SetString(maxFeePerGas, 0)
	}

	if maxPriorityFeePerGas != "" {
		opts.GasTipCap = new(big.Int)
		opts.GasTipCap.SetString(maxPriorityFeePerGas, 0)
	}

	if gasLimit != 0 {
		opts.GasLimit = gasLimit
	}

	opts.NoSend = noSend
}

func CreateTokenSenderCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "token-sender",
		Short: "Interact with the TokenSender contract",
		Run: func(cmd *cobra.Command, args []string) {
			cmd.Help()
		},
	}

	cmd.SetOut(os.Stdout)

	DeployGroup := &cobra.Group{
		ID: "deploy", Title: "Commands which deploy contracts",
	}
	cmd.AddGroup(DeployGroup)
	ViewGroup := &cobra.Group{
		ID: "view", Title: "Commands which view contract state",
	}
	TransactGroup := &cobra.Group{
		ID: "transact", Title: "Commands which submit transactions",
	}
	cmd.AddGroup(ViewGroup, TransactGroup)

	cmdDeployTokenSender := CreateTokenSenderDeploymentCommand()
	cmdDeployTokenSender.GroupID = DeployGroup.ID
	cmd.AddCommand(cmdDeployTokenSender)

	cmdViewFaucetTimeInterval := CreateFaucetTimeIntervalCommand()
	cmdViewFaucetTimeInterval.GroupID = ViewGroup.ID
	cmd.AddCommand(cmdViewFaucetTimeInterval)
	cmdViewLastSentTimestamp := CreateLastSentTimestampCommand()
	cmdViewLastSentTimestamp.GroupID = ViewGroup.ID
	cmd.AddCommand(cmdViewLastSentTimestamp)

	cmdTransactSend := CreateSendCommand()
	cmdTransactSend.GroupID = TransactGroup.ID
	cmd.AddCommand(cmdTransactSend)

	return cmd
}
