name: Prepare release game7 app

on:
    push:
        tags:
            - "game7-v*"

jobs:
    release-game7:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/create-release@v1
              id: create_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: "${{ github.ref_name }}"
                  body: |
                      Version ${{ github.ref_name }}.
                  draft: true
                  prerelease: false
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
    upload_assets:
        runs-on: ubuntu-20.04
        needs: create_release
        strategy:
            fail-fast: true
            matrix:
                os: ["linux", "darwin", "windows"]
                arch: ["386", "amd64", "arm64"]
                exclude:
                    - os: "darwin"
                      arch: "arm"
                    - os: "darwin"
                      arch: "386"
                    - os: "windows"
                      arch: "arm"
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.18.0
            - uses: actions/setup-go@v2
              with:
                  go-version: ^1.20.0

            - name: Install dependencies
              working-directory: ./web3
              run: npm install
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly
            - name: Run Hardhat compile
              working-directory: ./web3
              run: npx hardhat compile
            - name: Install seer
              run: go install github.com/G7DAO/seer@latest

            - name: Build ERC20 interface with seer
              run: seer evm generate --package ERC20 --output bindings/ERC20/ERC20.go --hardhat web3/artifacts/contracts/token/ERC20.sol/ERC20.json --cli --struct ERC20

            - name: Build TokenFaucet interface with seer
              run: seer evm generate --package TokenFaucet --output bindings/TokenFaucet/TokenFaucet.go --hardhat web3/artifacts/contracts/faucet/TokenFaucet.sol/TokenFaucet.json --cli --struct TokenFaucet

            - name: Build WrappedNativeToken interface with seer
              run: seer evm generate --package WrappedNativeToken --output bindings/WrappedNativeToken/WrappedNativeToken.go --hardhat web3/artifacts/contracts/token/WrappedNativeToken.sol/WrappedNativeToken.json --cli --struct WrappedNativeToken

            - name: Build Staker interface with seer
              run: seer evm generate --package Staker --output bindings/Staker/Staker.go --hardhat web3/artifacts/contracts/staking/Staker.sol/Staker.json --cli --struct Staker

            - name: Build PositionMetadata interface with seer
              run: seer evm generate --package PositionMetadata --output bindings/PositionMetadata/PositionMetadata.go --hardhat web3/artifacts/contracts/staking/PositionMetadata.sol/PositionMetadata.json --cli --struct PositionMetadata

            - name: Build MockERC20 interface with seer
              run: seer evm generate --package MockERC20 --output bindings/MockERC20/MockERC20.go --hardhat web3/artifacts/contracts/mock/tokens.sol/MockERC20.json --cli --struct MockERC20

            - name: Build MockERC721 interface with seer
              run: seer evm generate --package MockERC721 --output bindings/MockERC721/MockERC721.go --hardhat web3/artifacts/contracts/mock/tokens.sol/MockERC721.json --cli --struct MockERC721

            - name: Build MockERC1155 interface with seer
              run: seer evm generate --package MockERC1155 --output bindings/MockERC1155/MockERC1155.go --hardhat web3/artifacts/contracts/mock/tokens.sol/MockERC1155.json --cli --struct MockERC1155

            - name: Build TokenSender interface with seer
              run: seer evm generate --package TokenSender --output bindings/TokenSender/TokenSender.go --hardhat web3/artifacts/contracts/faucet/TokenSender.sol/TokenSender.json --cli --struct TokenSender

            - name: Build binary for each valid (GOOS, GOARCH) pair
              env:
                  GOOS: ${{ matrix.os }}
                  GOARCH: ${{ matrix.arch }}
              run: |
                  BUILD_DIR="${{ github.ref_name }}-${GOOS}-${GOARCH}"
                  EXTENSION=""
                  if [ "$GOOS" = "windows" ]; then
                    EXTENSION=".exe"
                  fi
                  mkdir "$BUILD_DIR"
                  cp README.md "$BUILD_DIR/README.md"
                  go build -o "$BUILD_DIR/game7${EXTENSION}" ./cmd/game7
                  zip -r "$BUILD_DIR.zip" "$BUILD_DIR"
            - name: Upload release asset for each valid (GOOS, GOARH) pair
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.create_release.outputs.upload_url }}
                  asset_path: ./${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.zip
                  asset_name: ${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.zip
                  asset_content_type: application/zip
